### ISSUE TITLE
!autojails

### ISSUE THREAD

**Issue by cryx3001** [Tommy228/serruriers_ttt_issues#14]
Ne retourne rien alors que des jails sont placées
(sauf quand aucune jail est en attente "Erreur : aucune jail en attente".)

**Comment by Butanal** [comment]
Je verrai, mais c'est une commande un peu foireuse que j'avais écrite quand je débutais en LUA, je sais pas si elle en vaut la peine x).

**Comment by Butanal** [comment]
Fixed (df2c30e4).
