### ISSUE TITLE
Sourceban

### ISSUE THREAD

**Issue by cryx3001** [Tommy228/serruriers_ttt_issues#15]
Les bans ne sont plus affichés dans le sourceban

**Comment by Butanal** [comment]
En effet, le sourcebans n'est pas encore intégralement migré. Je vais tenter de modifier directement la BDD utilisée par le site actuel.

**Comment by Butanal** [comment]
En fait il est intégralement migré, le nouveau site est à [cette addresse](https://sourcebans.lesserruriers.fr/) (je mettrai à jour sur le forum les raccourcis correspondants).
