### ISSUE TITLE
plugin Whitelist

### ISSUE THREAD

**Issue by IproNewtonCat** [Tommy228/serruriers_ttt_issues#20]
Impossible de whitelist un jour via evovle, celui ci nous retourne l'erreur suivante : 

Plugin 'Whitelist' failed with error:
addons/evolve/lua/ev_plugins/sh_whitelist.lua:28: attempt to call method 'UpdateWhitelist' (a nil value)

**Comment by Butanal** [comment]
C'est fix (08987b57).
