### ISSUE TITLE
ANTIJEUX Le fait de pouvoir laisser un message en étant transformer en tourelle

### ISSUE THREAD

**Issue by LucasPsy** [Tommy228/serruriers_ttt_issues#3]
On te transforme en tourelle et on a juste a écrire un message dans le chat sans appuyer sur enter et ce message est mit sur notre corp en tant que lastwords.
Alors que la tourelle devient un collègue des T, c'est pour cela que les moyens de communication ont été enlever

**Comment by Butanal** [comment]
Résolu (commit bb2661b5)
