### ISSUE TITLE
Le game tracker

### ISSUE THREAD

**Issue by PONEYARGENTE** [Tommy228/serruriers_ttt_issues#7]
Ce serait bien de changé sur le forum la page du game tracker avec le serveur actuel et non l'ancien serveur qui est lock .
Edit: s'il vous plait

RoyalCheese

**Comment by Butanal** [comment]
Je n'arrive même pas à trouver où ça se modifie (en cherchant les templates j'trouve rien), si tu sais @Tommy228 go.

**Comment by Tommy228** [comment]
Gros truc de merde, j'ai fait une recherche du mot-clef "gametracker" sur toutes les tables MySQL pour finir par tomber sur un BLOB qui contient le lien... j'ai édité ça directement en base, puis j'ai edité un autre style sur le panel admin pour qu'il recompile le CSS. Et ça a marché.

Après coup on ne sait toujours pas où on est censé changer ce truc sans méthode barbare, mais peu importe

**Comment by Tommy228** [comment]
Je suspecte que c'est quelque part dans les paramètres de style Xenforo, je conseille le port d'un casque de chantier avec lampe frontale avant de s'y aventurer.
