### ISSUE TITLE
Bug avec AWarn

### ISSUE THREAD

**Issue by cryx3001** [Tommy228/serruriers_ttt_issues#9]
Lors d'un changement de map : 
[AWarn] **NULL** joint le serveur. Avertissements Total: 2

Bon ce n'est pas dérangeant mais voilà

**Comment by Butanal** [comment]
Probablement l'entité joueur pas pleinement chargée, ça peut arriver mais à moins de retarder l'affichage du message c'est plus lié à Garry's Mod qu'à celui de AWarn.

**Comment by Tommy228** [comment]
Why, le message est affiché sur `PlayerInitialSpawn` ? On pourrait basculer à `PlayerAuthed` dans ce cas - le joueur est valide côté serveur et client quand`PlayerAuthed` est appelé.

**Comment by Butanal** [comment]
Fait (664be6f9)
